import { registry } from '../tool-registry.js';
import { createCategoryTool } from './create-category.tool.js';
import { listCategoriesTool } from './list-categories.tool.js';
import { saveLinkTool } from './save-link.tool.js';
import { listLinksTool } from './list-links.tool.js';
import { pickLinkTool } from './pick-link.tool.js';
import { deleteLinkTool } from './delete-link.tool.js';
import { scheduleReminderTool } from './schedule-reminder.tool.js';
import { listRemindersTool } from './list-reminders.tool.js';
import { cancelReminderTool } from './cancel-reminder.tool.js';
import { addContactTool } from './add-contact.tool.js';
import { listContactsTool } from './list-contacts.tool.js';
import { sendMessageTool } from './send-message.tool.js';
import { addTodoTool } from './add-todo.tool.js';
import { listTodosTool } from './list-todos.tool.js';
import { completeTodoTool } from './complete-todo.tool.js';
import { deleteTodoTool } from './delete-todo.tool.js';
import { editTodoTool } from './edit-todo.tool.js';
import { editReminderTool } from './edit-reminder.tool.js';
import { editRoutineTool } from './edit-routine.tool.js';
import { getTodayAgendaTool } from './get-today-agenda.tool.js';
import { createRoutineTool } from './create-routine.tool.js';
import { checkinRoutineTool } from './checkin-routine.tool.js';
import { routineProgressTool } from './routine-progress.tool.js';
import { scheduleImportantDateTool } from './schedule-important-date.tool.js';
import { scheduleFlexibleReminderTool } from './schedule-flexible-reminder.tool.js';
import { scheduleIntervalReminderTool } from './schedule-interval-reminder.tool.js';
import { registerRewardPunishmentTool } from './register-reward-punishment.tool.js';
import { listRewardsPunishmentsTool } from './list-rewards-punishments.tool.js';
import { deleteContactTool } from './delete-contact.tool.js';
import { deleteRoutineTool } from './delete-routine.tool.js';
import { deleteCategoryTool } from './delete-category.tool.js';
import { deleteRewardPunishmentTool } from './delete-reward-punishment.tool.js';
import { deleteReminderTool } from './delete-reminder.tool.js';
import { grantAccessTool } from './grant-access.tool.js';
import { revokeAccessTool } from './revoke-access.tool.js';
import { listUsersTool } from './list-users.tool.js';
import { setUserPermissionsTool } from './set-user-permissions.tool.js';
import { listAvailableToolsTool } from './list-available-tools.tool.js';
import { addExerciseTool } from './add-exercise.tool.js';
import { listExercisesTool } from './list-exercises.tool.js';
import { editExerciseTool } from './edit-exercise.tool.js';
import { deleteExerciseTool } from './delete-exercise.tool.js';
import { planMealTool } from './plan-meal.tool.js';
import { listMealPlanTool } from './list-meal-plan.tool.js';
import { deleteMealPlanTool } from './delete-meal-plan.tool.js';
import { saveRecipeTool } from './save-recipe.tool.js';
import { listRecipesTool } from './list-recipes.tool.js';
import { getRecipeTool } from './get-recipe.tool.js';
import { deleteRecipeTool } from './delete-recipe.tool.js';
import { regeneratePanelTokenTool } from './regenerate-panel-token.tool.js';

/** Registers every tool the agent can use. Called once at boot. */
export function registerTools(): void {
  registry.register(createCategoryTool);
  registry.register(listCategoriesTool);
  registry.register(saveLinkTool);
  registry.register(listLinksTool);
  registry.register(pickLinkTool);
  registry.register(deleteLinkTool);
  registry.register(scheduleReminderTool);
  registry.register(listRemindersTool);
  registry.register(cancelReminderTool);
  registry.register(addContactTool);
  registry.register(listContactsTool);
  registry.register(sendMessageTool);
  registry.register(addTodoTool);
  registry.register(listTodosTool);
  registry.register(completeTodoTool);
  registry.register(deleteTodoTool);
  registry.register(editTodoTool);
  registry.register(editReminderTool);
  registry.register(editRoutineTool);
  registry.register(getTodayAgendaTool);
  registry.register(createRoutineTool);
  registry.register(checkinRoutineTool);
  registry.register(routineProgressTool);
  registry.register(scheduleImportantDateTool);
  registry.register(scheduleFlexibleReminderTool);
  registry.register(scheduleIntervalReminderTool);
  registry.register(registerRewardPunishmentTool);
  registry.register(listRewardsPunishmentsTool);
  registry.register(deleteContactTool);
  registry.register(deleteRoutineTool);
  registry.register(deleteCategoryTool);
  registry.register(deleteRewardPunishmentTool);
  registry.register(deleteReminderTool);
  registry.register(grantAccessTool);
  registry.register(revokeAccessTool);
  registry.register(listUsersTool);
  registry.register(setUserPermissionsTool);
  registry.register(listAvailableToolsTool);
  registry.register(addExerciseTool);
  registry.register(listExercisesTool);
  registry.register(editExerciseTool);
  registry.register(deleteExerciseTool);
  registry.register(planMealTool);
  registry.register(listMealPlanTool);
  registry.register(deleteMealPlanTool);
  registry.register(saveRecipeTool);
  registry.register(listRecipesTool);
  registry.register(getRecipeTool);
  registry.register(deleteRecipeTool);
  registry.register(regeneratePanelTokenTool);
}
