import { registry } from '../tool-registry.js';
import { createCategoryTool } from './create-category.tool.js';
import { listCategoriesTool } from './list-categories.tool.js';
import { saveLinkTool } from './save-link.tool.js';
import { listLinksTool } from './list-links.tool.js';
import { pickLinkTool } from './pick-link.tool.js';
import { deleteLinkTool } from './delete-link.tool.js';
import { scheduleReminderTool } from './schedule-reminder.tool.js';
import { listRemindersTool } from './list-reminders.tool.js';
import { cancelReminderTool } from './cancel-reminder.tool.js';
import { addContactTool } from './add-contact.tool.js';
import { listContactsTool } from './list-contacts.tool.js';
import { sendMessageTool } from './send-message.tool.js';
import { addTodoTool } from './add-todo.tool.js';
import { listTodosTool } from './list-todos.tool.js';
import { completeTodoTool } from './complete-todo.tool.js';
import { deleteTodoTool } from './delete-todo.tool.js';
import { editTodoTool } from './edit-todo.tool.js';
import { editReminderTool } from './edit-reminder.tool.js';
import { editRoutineTool } from './edit-routine.tool.js';
import { getTodayAgendaTool } from './get-today-agenda.tool.js';
import { getWeekReportTool } from './get-week-report.tool.js';
import { createRoutineTool } from './create-routine.tool.js';
import { checkinRoutineTool } from './checkin-routine.tool.js';
import { routineProgressTool } from './routine-progress.tool.js';
import { scheduleImportantDateTool } from './schedule-important-date.tool.js';
import { scheduleFlexibleReminderTool } from './schedule-flexible-reminder.tool.js';
import { scheduleIntervalReminderTool } from './schedule-interval-reminder.tool.js';
import { registerRewardPunishmentTool } from './register-reward-punishment.tool.js';
import { listRewardsPunishmentsTool } from './list-rewards-punishments.tool.js';
import { deleteContactTool } from './delete-contact.tool.js';
import { deleteRoutineTool } from './delete-routine.tool.js';
import { deleteCategoryTool } from './delete-category.tool.js';
import { deleteRewardPunishmentTool } from './delete-reward-punishment.tool.js';
import { deleteReminderTool } from './delete-reminder.tool.js';
import { grantAccessTool } from './grant-access.tool.js';
import { revokeAccessTool } from './revoke-access.tool.js';
import { listUsersTool } from './list-users.tool.js';
import { setUserPermissionsTool } from './set-user-permissions.tool.js';
import { listPermissionsTool } from './list-permissions.tool.js';
import { getUserPermissionsTool } from './get-user-permissions.tool.js';
import { managePermissionPackageTool } from './manage-permission-package.tool.js';
import { setWebPasswordTool } from './set-web-password.tool.js';
import { changeWebPasswordTool } from './change-web-password.tool.js';
import { registerSchedulingTools } from '../../scheduling/tools/index.js';
import { addExerciseTool } from './add-exercise.tool.js';
import { listExercisesTool } from './list-exercises.tool.js';
import { editExerciseTool } from './edit-exercise.tool.js';
import { deleteExerciseTool } from './delete-exercise.tool.js';
import { planMealTool } from './plan-meal.tool.js';
import { listMealPlanTool } from './list-meal-plan.tool.js';
import { deleteMealPlanTool } from './delete-meal-plan.tool.js';
import { saveRecipeTool } from './save-recipe.tool.js';
import { listRecipesTool } from './list-recipes.tool.js';
import { getRecipeTool } from './get-recipe.tool.js';
import { deleteRecipeTool } from './delete-recipe.tool.js';
import { pauseNotificationsTool } from './pause-notifications.tool.js';
import { resumeNotificationsTool } from './resume-notifications.tool.js';
import { pauseReminderTool } from './pause-reminder.tool.js';
import { resumeReminderTool } from './resume-reminder.tool.js';
import { pauseRoutineTool } from './pause-routine.tool.js';
import { resumeRoutineTool } from './resume-routine.tool.js';
import { editLinkTool } from './edit-link.tool.js';
import { editCategoryTool } from './edit-category.tool.js';
import { editContactTool } from './edit-contact.tool.js';
import { editMealPlanTool } from './edit-meal-plan.tool.js';
import { editRecipeTool } from './edit-recipe.tool.js';
import { showMenuTool } from './show-menu.tool.js';
import { addNoteTool } from './add-note.tool.js';
import { listNotesTool } from './list-notes.tool.js';
import { editNoteTool } from './edit-note.tool.js';
import { deleteNoteTool } from './delete-note.tool.js';
import { scheduleCallReminderTool } from './schedule-call-reminder.tool.js';
import { listCallRemindersTool } from './list-call-reminders.tool.js';
import { editCallReminderTool } from './edit-call-reminder.tool.js';
import { cancelCallReminderTool } from './cancel-call-reminder.tool.js';
import { deleteCallReminderTool } from './delete-call-reminder.tool.js';
import { sendStickerTool } from './send-sticker.tool.js';
import { listStickersTool } from './list-stickers.tool.js';
import { deleteStickerTool } from './delete-sticker.tool.js';
import { announceUpdateTool } from './announce-update.tool.js';
import { setUserGenderTool } from './set-user-gender.tool.js';
import { setVoiceGenderTool } from './set-voice-gender.tool.js';
import { setFashionProfileTool } from './set-fashion-profile.tool.js';
import { createListTool } from './create-list.tool.js';
import { addListItemTool } from './add-list-item.tool.js';
import { listListsTool } from './list-lists.tool.js';
import { viewListTool } from './view-list.tool.js';
import { checkListItemTool } from './check-list-item.tool.js';
import { deleteListItemTool } from './delete-list-item.tool.js';
import { deleteListTool } from './delete-list.tool.js';

/** Registers every tool the agent can use. Called once at boot. */
export function registerTools(): void {
  registry.register(createCategoryTool);
  registry.register(listCategoriesTool);
  registry.register(saveLinkTool);
  registry.register(listLinksTool);
  registry.register(pickLinkTool);
  registry.register(deleteLinkTool);
  registry.register(scheduleReminderTool);
  registry.register(listRemindersTool);
  registry.register(cancelReminderTool);
  registry.register(addContactTool);
  registry.register(listContactsTool);
  registry.register(sendMessageTool);
  registry.register(addTodoTool);
  registry.register(listTodosTool);
  registry.register(completeTodoTool);
  registry.register(deleteTodoTool);
  registry.register(editTodoTool);
  registry.register(editReminderTool);
  registry.register(editRoutineTool);
  registry.register(getTodayAgendaTool);
  registry.register(getWeekReportTool);
  registry.register(createRoutineTool);
  registry.register(checkinRoutineTool);
  registry.register(routineProgressTool);
  registry.register(scheduleImportantDateTool);
  registry.register(scheduleFlexibleReminderTool);
  registry.register(scheduleIntervalReminderTool);
  registry.register(registerRewardPunishmentTool);
  registry.register(listRewardsPunishmentsTool);
  registry.register(deleteContactTool);
  registry.register(deleteRoutineTool);
  registry.register(deleteCategoryTool);
  registry.register(deleteRewardPunishmentTool);
  registry.register(deleteReminderTool);
  registry.register(grantAccessTool);
  registry.register(revokeAccessTool);
  registry.register(listUsersTool);
  registry.register(setUserPermissionsTool);
  registry.register(listPermissionsTool);
  registry.register(getUserPermissionsTool);
  registry.register(managePermissionPackageTool);
  registry.register(setWebPasswordTool);
  registry.register(changeWebPasswordTool);
  registry.register(addExerciseTool);
  registry.register(listExercisesTool);
  registry.register(editExerciseTool);
  registry.register(deleteExerciseTool);
  registry.register(planMealTool);
  registry.register(listMealPlanTool);
  registry.register(deleteMealPlanTool);
  registry.register(saveRecipeTool);
  registry.register(listRecipesTool);
  registry.register(getRecipeTool);
  registry.register(deleteRecipeTool);
  registry.register(pauseNotificationsTool);
  registry.register(resumeNotificationsTool);
  registry.register(pauseReminderTool);
  registry.register(resumeReminderTool);
  registry.register(pauseRoutineTool);
  registry.register(resumeRoutineTool);
  registry.register(editLinkTool);
  registry.register(editCategoryTool);
  registry.register(editContactTool);
  registry.register(editMealPlanTool);
  registry.register(editRecipeTool);
  registry.register(showMenuTool);
  registry.register(addNoteTool);
  registry.register(listNotesTool);
  registry.register(editNoteTool);
  registry.register(deleteNoteTool);
  registry.register(scheduleCallReminderTool);
  registry.register(listCallRemindersTool);
  registry.register(editCallReminderTool);
  registry.register(cancelCallReminderTool);
  registry.register(deleteCallReminderTool);
  registry.register(sendStickerTool);
  registry.register(listStickersTool);
  registry.register(deleteStickerTool);
  registry.register(announceUpdateTool);
  registry.register(setUserGenderTool);
  registry.register(setVoiceGenderTool);
  registry.register(setFashionProfileTool);
  registry.register(createListTool);
  registry.register(addListItemTool);
  registry.register(listListsTool);
  registry.register(viewListTool);
  registry.register(checkListItemTool);
  registry.register(deleteListItemTool);
  registry.register(deleteListTool);
  registerSchedulingTools(registry);
}
